name: bucket_pull_request
on:
  pull_request:
    branches:
      - master
jobs:
  bucket_pull_request:
    env:
      BUCKET_NAME: 'lpfannsite'
    runs-on: ubuntu-latest
    name: Create a Textile Bucket
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.64.0'
        extended: true

    - name: Build
      run: hugo --minify
    - name: Bucket push action
      id: push
      uses: textileio/github-action-bucket-push@master
      with:
        bucket-name: '${{ env.BUCKET_NAME }}-${{ github.event.pull_request.id }}'
        path: 'public/*'
        token: ${{ secrets.TEXTILE_AUTH_TOKEN }}
    - name: Get the output CID
      run: echo "The CID was ${{ steps.push.outputs.cid }}"
    - name: Get the Bucket URL
      run: echo "The Bucket URL is ${{ steps.push.outputs.url }}"
